In [11]:
import numpy as np

In [25]:
data=np.genfromtxt("data/ratings.dat", delimiter="::",dtype=np.int64)

In [14]:
print(data[:10,:])
print(data.shape)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]]
(1000209, 4)


In [15]:
user_ids=np.unique(data[:,0])
print(user_ids[:5])
print(user_ids.shape)

[1 2 3 4 5]
(6040,)


In [19]:
mean_values=[]
for user_id in user_ids:
    data_for_user=data[data[:,0]==user_id, :]
    value=data_for_user[:,2].mean()
    mean_values.append([user_id, value])

In [20]:
mean_values[:10]

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606]]

In [23]:
mean_array=np.array(mean_values, dtype=np.float32)
print(mean_array[:10])
print(mean_array.shape)

[[ 1.         4.188679 ]
 [ 2.         3.7131784]
 [ 3.         3.9019608]
 [ 4.         4.1904764]
 [ 5.         3.1464646]
 [ 6.         3.9014084]
 [ 7.         4.322581 ]
 [ 8.         3.884892 ]
 [ 9.         3.7358491]
 [10.         4.114713 ]]
(6040, 2)


In [24]:
np.savetxt("data/ratings.dat_result.csv", mean_array, fmt="%.2f", delimiter=",")

In [26]:
movie_ids=np.unique(data[:,1])
print(movie_ids[:10])
print(movie_ids.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(3706,)


In [29]:
movie_mean_values=[]

In [30]:
for movie_id in movie_ids:
    data_for_movie=data[data[:,1]==movie_id,:]
    value=data_for_movie[:,2].mean()
    movie_mean_values.append([movie_id, value])

In [31]:
movie_mean_values[:10]

[[1, 4.146846413095811],
 [2, 3.20114122681883],
 [3, 3.01673640167364],
 [4, 2.7294117647058824],
 [5, 3.0067567567567566],
 [6, 3.8787234042553194],
 [7, 3.410480349344978],
 [8, 3.014705882352941],
 [9, 2.656862745098039],
 [10, 3.5405405405405403]]

In [34]:
movie_mean_array=np.array(movie_mean_values, dtype=np.float32)
print(movie_mean_array[:10])
print(movie_mean_array.shape)

[[ 1.         4.1468463]
 [ 2.         3.201141 ]
 [ 3.         3.0167365]
 [ 4.         2.7294118]
 [ 5.         3.0067568]
 [ 6.         3.8787234]
 [ 7.         3.4104803]
 [ 8.         3.014706 ]
 [ 9.         2.6568627]
 [10.         3.5405405]]
(3706, 2)


In [35]:
np.savetxt('data/movie_result.csv', movie_mean_array, fmt="%.2f", delimiter=',')