In [29]:
import numpy as np


In [30]:
a=[1,2,3,4,5]
b= np.array(a)
print(a, type(a))
print(b, type(b))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [31]:
b=np.arange(1,10,2)
print(b, type(b), b.shape)

[1 3 5 7 9] <class 'numpy.ndarray'> (5,)


In [32]:
a= [[1,2,3],[4,5,6]]
b=np.array(a)
print(b, b.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [33]:
a=[1,2,3,4,5,6]
b=np.array(a).reshape(2,3)
c=np.array(a).reshape(3,2)
print(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [34]:
print(b[0])
print(b[1][2])
print(b[:,])

[1 2 3]
6
[[1 2 3]
 [4 5 6]]


In [35]:
a=[[1,2,3],[4,5,6]]

print(a[:],[1])

[[1, 2, 3], [4, 5, 6]] [1]


In [36]:
print(a)
print(b)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [37]:
print(a*2)
print(b*2)

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [38]:
aa=[1,2,3,4]
bb=[7,8]
arr1=np.array(aa)
arr2=np.array(bb)
print(aa+bb)
print(arr1+3)
print(arr1-1)
print(arr1*2)
print(arr1/2)
print(arr1//2)
print(arr1**2)
print(arr1%2)

[1, 2, 3, 4, 7, 8]
[4 5 6 7]
[0 1 2 3]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[ 1  4  9 16]
[1 0 1 0]


In [39]:
a1=[[1,1,1],[2,2,2],[3,3,3]]
a2=[1,2,3]
b1 = np.array(a1)
b2=np.array(a2)
print(b1)
print(b2)
print(b1+b2)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[1 2 3]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [40]:
print(b1)
print(b1.sum())
print(np.sum(b1))
print(b1.sum(axis=1))
#mean, sqrt, max, min, log

[[1 1 1]
 [2 2 2]
 [3 3 3]]
18
18
[3 6 9]


In [41]:
print(b1.mean)
print(np.sqrt(b1))
print(np.max(b1))
print(np.min(b1))
print(np.log(b1))

<built-in method mean of numpy.ndarray object at 0x0000021C7235C210>
[[1.         1.         1.        ]
 [1.41421356 1.41421356 1.41421356]
 [1.73205081 1.73205081 1.73205081]]
3
1
[[0.         0.         0.        ]
 [0.69314718 0.69314718 0.69314718]
 [1.09861229 1.09861229 1.09861229]]


In [49]:
print(np.sort(arr1))
print(np.sort(arr1, axis=1))
print(np.sort(arr1, axis=0))
print(np.sort(arr1, axis=0)[::-1,::])
print(np.sort(arr1, axis=1)[::,::-1])

[1 2 3 4]


AxisError: axis 1 is out of bounds for array of dimension 1

In [50]:
print(arr1)
print(arr1.transpose())

[1 2 3 4]
[1 2 3 4]


In [52]:
print(arr1)
b1=np.ones_like(arr1)
b2=np.zeros_like(arr1)
print(b1)
print(b2)

[1 2 3 4]
[1 1 1 1]
[0 0 0 0]
