In [11]:
import numpy as np

In [13]:
data=np.genfromtxt("data/ratings.dat", delimiter="::",dtype=np.int64)

In [14]:
print(data[:10,:])
print(data.shape)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]]
(1000209, 4)


In [15]:
user_ids=np.unique(data[:,0])
print(user_ids[:5])
print(user_ids.shape)

[1 2 3 4 5]
(6040,)


In [19]:
mean_values=[]
for user_id in user_ids:
    data_for_user=data[data[:,0]==user_id, :]
    value=data_for_user[:,2].mean()
    mean_values.append([user_id, value])

In [20]:
mean_values[:10]

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606]]

In [ ]:
mean_array=np.array(mean_values, dtype=np.float32)
print(mean_array)